[package]
name = "ZSMM"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["tokio", "image"] }
iced_core = "0.13.2"
tokio = { version = "1.47.1", features = ["full"] }
itertools = { version = "0.14.0" }
